### ISSUE TITLE
Việt Speech to Text

### ISSUE THREAD

**Issue by anhnhatanh** [undertheseanlp/automatic_speech_recognition#21]
Mình đang cần một ứng dụng chạy offline trên môi trường Windows để giải quyết vấn đề Việt Speech to Text. Các bạn có thể tư vấn cụ thể làm như thế nào, step 2 step ... (mã nguồn, cách training hoặc bằng cách nào đó thiết lập một hệ thống chạy độc lập hoặc trên trên môi trường mạngLAN cũng được)
Dùng không cần Internet mà giải quyết được.
Vì trước tới giờ mình toàn dùng Google Docs để chuyển giọng đọc thành text..hihi.

**Comment by rain1024** [comment]
Chào @anhnhatanh 

Hiện tại, nhóm mình vẫn đang hoàn thiện repository này. Tuy nhiên, nhóm mình lại không support Windows.

@anhnhatanh có thể tìm các giải pháp khác có hỗ trợ Windows nhé.

**Comment by anhnhatanh** [comment]
Cảm ơn Vu Anh nhiều, nhóm của Vu Anh thực hiện trên môi trương nào? có thể
cho mình tìm hiểu cùng?
Rất mong sự hỗ trợ nhiệt tình của cả nhóm.
Thân chào và hẹn gặp lại.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Vào Th 4, 28 thg 11, 2018 vào lúc 07:33 Vu Anh <notifications@github.com>
đã viết:

**Comment by rain1024** [comment]
Hiện tại, nhóm mình đang làm việc trên môi trường Ubuntu, sử dụng kaldi. Kết quả đang khá thấp 20% WER trên tập test VLSP 2018

Nếu bạn có quan tâm chạy thử theo hướng dẫn tại [https://github.com/undertheseanlp/automatic_speech_recognition#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng](https://github.com/undertheseanlp/automatic_speech_recognition#h%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-s%E1%BB%AD-d%E1%BB%A5ng)

**Comment by anhnhatanh** [comment]
Tks Vu Anh, mình không rành về Ubuntu, mình sẽ cài và test thử xem, có khó
khăn gì Vu Anh và nhóm giúp nha....hihihi


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Vào Th 2, 3 thg 12, 2018 vào lúc 12:52 Vu Anh <notifications@github.com>
đã viết:

**Comment by anhnhatanh** [comment]
Vu Anh ơi, mình đã cài Ubuntu 18.04 rồi, nhờ bạn giúp mình nêu từng bước cài đặt cụ thể để chạy thành công Demo trên được không?, like Vu Anh mạnh !..

**Comment by rain1024** [comment]
@anhnhatanh nice

@anhnhatanh bắt đầu từ hướng dẫn này nhé 

@Pubbus giúp anh support bạn @anhnhatanh nhé

**Comment by Pubbus** [comment]
Vâng anh.

**Comment by vanthanhcong1111** [comment]
Chào nhóm tác giả, mình cũng đang muốn áp dụng sản phẩm như vậy vào công việc của mình, không biết sản phẩm này có chạy offline trong LAN được không?

**Comment by rain1024** [comment]
@vanthanhcong1111 Hệ thống này bạn có thể cài đặt offline được. Nhưng hiện tại độ chính xác của hệ thống chỉ phù hợp với các bài toán có tập từ nhỏ, đối với bài toán tập từ lớn, cần lượng dữ liệu khá lớn để đảm bảo chất lượng có thể áp dụng trong sản phẩm thực tế.

Chúc bạn thành công!

**Comment by vanthanhcong1111** [comment]
Cảm ơn nhóm tác giả, mình sẽ cài đặt và dùng thử. Mình có tập từ kha khá, chắc phải training nhiều để tăng độ chính xác.

**Comment by anhnhatanh** [comment]
Với sự trợ giúp nhiệt tình của Mr Lê Phi Hùng, mình đã cài đặt và chạy được lệnh Train.py trên Unbuntu 18.04. Mình thấy sau khi Train xong, thư mục Kaldi-Trunk có dung lượng rất lớn khoảng hơn 10Gb không biết có làm sai gì không?. Và câu hỏi lớn thứ 2, ví dụ mình có 1 file ghi âm hoặc muốn đọc trực tiếp vào Micro trên máy vi tính cho nhận dạng thì làm thế nào? rất mong nhận sự trợ giúp tiếp của AE. Tks AE nhiều!

**Comment by anhnhatanh** [comment]
> 
> 
> Chào nhóm tác giả, mình cũng đang muốn áp dụng sản phẩm như vậy vào công việc của mình, không biết sản phẩm này có chạy offline trong LAN được không?

Good quá, mình là member new có gì xin chia sẻ và trợ giúp nha @vanthanhcong1111??
