### ISSUE TITLE
Lỗi không tìm thấy file

### ISSUE THREAD

**Issue by hainmit09** [undertheseanlp/automatic_speech_recognition#27]
Chào các bạn, mình bị lỗi này có ai biết không giúp mình với,mình cảm ơn rất nhiều
1. Sau khi build xong mình chạy predict thì bị lỗi
Can't open transcriptions/one-best.tra: No such file or directory at /root/kaldi                                                                                        -trunk/egs/uts_601/utils/int2sym.pl line 57.
2. Câu lệnh predict của mình là
python /data/automatic_speech_recognition-master/egs/vivos/predict.py --wav /root/vivos/train/waves/VIVOSSPK01/VIVOSSPK01_R001.wav --kaldi_folder ~/kaldi-trunk --model_path ~/kaldi-trunk/egs/uts_601/exp/tri3a --utils_path /root/kaldi-trunk/egs/uts_601/utils

Mình có làm sai gì không, cảm ơn đã đọc và hỗ trợ nhiều

**Comment by Pubbus** [comment]
Bạn thêm parameter **--method lda_mllt** nhé.

**Comment by hainmit09** [comment]
Cảm ơn bạn đã trả lời ,
Cho mình hỏi thêm chút là các method sat và delta đều dùng param  --method lda_mllt khi predict phải không bạn, cái code predict cho 2 phần này chưa hoàn thiện.

Tuy nhiên dùng param này để predict model cho 2 phương pháp là train cho deltadelta và sat thì sai nhiều quá

**Comment by Pubbus** [comment]
> các method sat và delta đều dùng param --method lda_mllt khi predict
Bạn train bằng method nào thì dùng param method đó tương ứng cho predict nhé. 

> cái code predict cho 2 phần này chưa hoàn thiện
Đúng rồi bạn, team đang hoàn thiện phần này. Sẽ cập nhật sớm nhất có thể.

**Comment by rain1024** [comment]
> Tuy nhiên dùng param này để predict model cho 2 phương pháp là train cho deltadelta và sat thì sai nhiều quá

Hiện tại dữ liệu huấn luyện cho bài này còn quá ít. @hainmit09 có thể đóng góp được gì không?

**Comment by hainmit09** [comment]
Mình sẽ cố gắng đóng góp nhiều nhất có thể, cảm ơn nhóm đã chia sẻ

**Comment by haidaqn** [comment]
> Bạn thêm parameter **--method lda_mllt** nhé.

thêm vào đâu ạ
