### ISSUE TITLE
Giúp đỡ: Mình thấy bạn có build thành pack của vosk

### ISSUE THREAD

**Issue by thongst02** [undertheseanlp/automatic_speech_recognition#39]
Xin chào team,
Mình thấy bạn có build 1 gói cho bên vosk, mong bạn hướng dẫn mình sau khi train.py xong thì build thành pack như vậy.
Cám ơn team.

**Comment by rain1024** [comment]
@Pubbus trả lời giúp bạn @thongst02 câu hỏi này nhé ;)

**Comment by luiyen** [comment]
Xin chào @thongst02, sau khi bạn chạy theo hướng dẫn thì sẽ có model pack trong đường dẫn: 
{kaldi-path}/egs/{uts_*}/exp/{model}/

**Comment by thongst02** [comment]
Chào bạn,
Mình có vào thư mục đó rồi, nhưng mình muốn train nnet3 thì toàn báo lỗi,
mà các server có sẵn thì toàn phải dùng nnet 3 @@.
Cám ơn bạn.

Vào CN, 5 thg 7, 2020 vào lúc 12:33 Hung Le <notifications@github.com> đã
viết:
