### ISSUE TITLE
Hỏi về hướng dẫn trước khi chạy train.py

### ISSUE THREAD

**Issue by thien1311** [undertheseanlp/automatic_speech_recognition#41]
Mình đọc trong hướng dẫn thấy nói, là "set đường dẫn tới kaldi_folder trước khi run" vậy cho mình hỏi kaldi_folder nằm ở đâu vậy và còn "N_TRAIN và N_TEST trong init của KaldiSpeechRecognition" nằm ở đâu. Cám ơn bạn đã đọc và trả lời

**Comment by datdao1998** [comment]
@thien1311  khi cài đặt kaldi như hướng dẫn thì ở đường dẫn root có file kaldi-trunk, bạn chỉ cần set đường dẫn tới nó là được, Còn N_TRAIN và N_TEST ở trong file egs/vivos/extension/model.py nhé.

**Comment by thien1311** [comment]
cám ơn bạn mình đã mò được và run thành công project rồi
