### ISSUE TITLE
WER quá cao

### ISSUE THREAD

**Issue by hungcuiga1** [undertheseanlp/automatic_speech_recognition#42]
WER là tỉ lệ lỗi từ. Trong này đề cập ở khoảng 70 80% liệu có phải quá cao không

**Comment by luiyen** [comment]
@hungcuiga1 kết quả trong README sử dụng tập dữ liệu cơ bản nên WER sẽ khá cao với các tập test nhé. Thêm dữ liệu được chuẩn hoá có thể cải thiện WER
